### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'str'

### ISSUE THREAD

**Issue by KAKAROT12419** [ZFTurbo/Mean-Average-Precision-for-Boxes#5]
I think this error is fixed in repo but it is showing error whenever, i am calling map function in my code.

**Comment by salih-ds** [comment]
> I think this error is fixed in repo but it is showing error whenever, i am calling map function in my code.

it does not work by pip

you can clone repo and use function:

!git clone https://github.com/ZFTurbo/Mean-Average-Precision-for-Boxes.git

import importlib  
map_boxes = importlib.import_module("Mean-Average-Precision-for-Boxes.map_boxes.__init__")
mean_average_precision_for_boxes = map_boxes.mean_average_precision_for_boxes

**Comment by ZFTurbo** [comment]
If you use repo from pip - it doesn't have latest updates yet. I will add ASAP. Or you can install more older version of numpy.

**Comment by ZFTurbo** [comment]
I added release 1.0.6 in pypi. Now install from pip must works ok.
