### ISSUE TITLE
Regarding the threshold setting

### ISSUE THREAD

**Issue by Peter-zzk** [ZFTurbo/Mean-Average-Precision-for-Boxes#6]
Hello, may I ask what the threshold for calculating the map for this project is?
I would greatly appreciate it if you could answer

**Comment by ZFTurbo** [comment]
By default it's 0.5:
https://github.com/ZFTurbo/Mean-Average-Precision-for-Boxes/blob/ba071697ed00dff61084faa5072740659a13075f/map_boxes/__init__.py#L93

You can change it with parameter `iou_threshold`.

**Comment by Peter-zzk** [comment]
Okay, thank you very much. This is very important to me
